customers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from customers.views import CustomerAutocomplete


urlpatterns = [               
    url(r'^customer-autocomplete/$',CustomerAutocomplete.as_view(),name='customer_autocomplete'),
    
    url(r'^$', views.dashboard,name='dashboard'), 
    
    url(r'^customer/create/$',views.create,name='create'),
    url(r'^customer/view/$',views.customers,name='customers'),
    url(r'^customer/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^customer/views/(?P<pk>.*)/$',views.customer,name='customer'),
    url(r'^customer/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^customer/delete-selected/$', views.delete_selected_customers, name='delete_selected_customers'), 

    url(r'^get-debit/$', views.get_credit, name='get_credit'),
    url(r'^check-document/$', views.check_document, name='check_document'),
]

finance/urls.py
from django.conf.urls import url
import views
from finance.autocomplete_light_registry import StaffAutocomplete, TaxCategoryAutocomplete


urlpatterns = [
    url(r'^tax_category-autocomplete/$',TaxCategoryAutocomplete.as_view(create_field='tax'),name='tax_category_autocomplete'),

    url(r'^$', views.dashboard,name='dashboard'), 

    url(r'^bank-account/create/$',views.create_bank_account,name='create_bank_account'),
    url(r'^bank-account/edit(?P<pk>.*)/$',views.edit_bank_account,name='edit_bank_account'),
    url(r'^bank-accounts/$',views.bank_accounts,name='bank_accounts'),
    url(r'^bank-account/view/(?P<pk>.*)/$',views.bank_account,name='bank_account'),
    url(r'^bank-account/delete/(?P<pk>.*)/$',views.delete_bank_account,name='delete_bank_account'),
    url(r'^bank-account/delete-selected/$', views.delete_selected_bank_accounts, name='delete_selected_bank_accounts'),

    url(r'^cash-account/create/$',views.create_cash_account,name='create_cash_account'),
    url(r'^cash-account/edit/(?P<pk>.*)$',views.edit_cash_account,name='edit_cash_account'),
    url(r'^cash-accounts/$',views.cash_accounts,name='cash_accounts'),
    url(r'^cash-account/view/(?P<pk>.*)/$',views.cash_account,name='cash_account'),
    url(r'^cash-account/delete/(?P<pk>.*)$',views.delete_cash_account,name='delete_cash_account'),
    url(r'^cash-account/delete-selected/$', views.delete_selected_cash_accounts, name='delete_selected_cash_accounts'),

    url(r'^transaction-category/create/$',views.create_transaction_category,name='create_transaction_category'),
    url(r'^transaction-category/edit/(?P<pk>.*)/$',views.edit_transaction_category,name='edit_transaction_category'),
    url(r'^transaction-categories/',views.transaction_categories,name='transaction_categories'),
    url(r'^transaction-category/view/(?P<pk>.*)/$',views.transaction_category,name='transaction_category'),
    url(r'^transaction-category/delete/(?P<pk>.*)/$',views.delete_transaction_category,name='delete_transaction_category'),
    url(r'^transaction-category/delete-selected/$', views.delete_selected_transaction_categories, name='delete_selected_transaction_categories'),

    url(r'^income/create/$',views.create_income,name='create_income'),
    url(r'^income/edit/(?P<pk>.*)/$',views.edit_income,name='edit_income'),
    
    url(r'^transactions/$',views.transactions,name='transactions'),
    url(r'^transaction/view/(?P<pk>.*)/$',views.transaction,name='transaction'),
    url(r'^transaction/delete/(?P<pk>.*)/$',views.delete_transaction,name='delete_transaction'),
    url(r'^transaction/delete-selected/$', views.delete_selected_transactions, name='delete_selected_transactions'),

    url(r'^expense/create/$',views.create_expense,name='create_expense'),
    url(r'^expense/edit(?P<pk>.*)/$',views.edit_expense,name='edit_expense'),
    
    url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staff_autocomplete'),

    url(r'^tax-category/create/$', views.create_tax_category, name='create_tax_category'),
    url(r'^tax-categories/$', views.tax_categories, name='tax_categories'),
    url(r'^tax-category/edit/(?P<pk>.*)/$', views.edit_tax_category, name='edit_tax_category'),
    url(r'^tax-category/(?P<pk>.*)/$', views.tax_category, name='tax_category'),
    url(r'^delete-tax-category/(?P<pk>.*)/$', views.delete_tax_category, name='delete_tax_category'),
    url(r'^tax-category/delete-selected/$', views.delete_selected_tax_categories, name='delete_selected_tax_categories'),

    url(r'^create-salary-payment/$',views.create_salary_payment,name='create_salary_payment'),
    url(r'^create-salary-payment-popup/$',views.create_salary_payment_ajax,name='create_salary_payment_ajax'),
    url(r'^salary-payment/edit/(?P<pk>.*)/$',views.edit_salary_payment,name='edit_salary_payment'),
    url(r'^salary-payments/$',views.salary_payments,name='salary_payments'),
    
]

hotel_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^web/', include('web.urls', namespace="web")), 

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),
      
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'), 
    
    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")), 
    url(r'^app/rooms/', include('rooms.urls', namespace="rooms")), 
    url(r'^app/bookings/', include('bookings.urls', namespace="bookings")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")), 
    url(r'^app/staffs/', include('staffs.urls', namespace='staffs')),
    url(r'^app/vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^app/purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^app/finance/', include('finance.urls', namespace="finance")),
    url(r'^app/tasks/', include('tasks.urls', namespace="tasks")),
    
    url(r'^app/users/', include('users.urls', namespace="users")), 

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),
    
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

web/urls.py
from django.conf.urls import url,include
import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

finance/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from main.models import BaseModel
from django.core.validators import MinValueValidator
from decimal import Decimal


TRANSACTION_CATEGORIES = (
    ('income','Income'),
    ('expense','Expense'),
)

TRANSACTION_MODE = (
    ('cash','Cash'),
    ('bank','Bank'),
)

PAYMENT_MODE = (
    ('cheque_payment','Cheque Payment'),
    ('internet_banking','Internet Banking'),
    ('card_payment','Card Payment'),
)

PAYMENT_TO = (
    ('cash_account','Cash Account'),
    ('bank_account','Bank Account'),
)

ACC_TYPE = (
    ('savings','Savings'),
    ('current','Current'),
)


class CashAccount(BaseModel):
    shop = models.ForeignKey("main.Shop")
    user = models.ForeignKey("auth.User")
    name = models.CharField(max_length=128)
    is_system_generated = models.BooleanField(default=False)
    first_time_balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'cash_account'
        verbose_name = _('cash account')
        verbose_name_plural = _('cash accounts')
        ordering = ('name',)
        
    class Admin:
        list_display = ('name',)
        
    def __unicode__(self):
        return self.name
    

class BankAccount(BaseModel):
    shop = models.ForeignKey("main.Shop")
    name = models.CharField(max_length=128)
    ifsc = models.CharField(max_length=128)
    branch = models.CharField(max_length=128)
    account_type = models.CharField(max_length=128,choices=ACC_TYPE)
    account_no = models.CharField(max_length=128)
    first_time_balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    # Balance to be added, its a self function
    
    class Meta:
        db_table = 'bank_account'
        verbose_name = _('bank account')
        verbose_name_plural = _('bank accounts')
        ordering = ('name',)
        
    class Admin:
        list_display = ('name',)
        
    def __unicode__(self):
        return self.name
    

class TransactionCategory(BaseModel):
    shop = models.ForeignKey("main.Shop")
    name = models.CharField(max_length=128)
    category_type = models.CharField(max_length=7,choices=TRANSACTION_CATEGORIES)
    is_system_generated = models.BooleanField(default=False)
    
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transaction_category'
        verbose_name = 'transaction category'
        verbose_name_plural = 'transaction categories'
        ordering = ('category_type',)
        unique_together = (('category_type','name'),)
        
    class Admin:
        list_display = ('name', 'category_type', 'is_system_generated')
        
    def __unicode__(self):
        return self.name


class TaxCategory(BaseModel):
    shop = models.ForeignKey("main.Shop")
    name = models.CharField(max_length=128)
    tax = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'tax_category'
        verbose_name = 'tax category'
        verbose_name_plural = 'tax categories'
        
    class Admin:
        list_display = ('name')
        
    def __unicode__(self):
        return self.name

    
class Transaction(BaseModel):
    staff = models.ForeignKey("staffs.Staff",null=True,blank=True)   
    shop = models.ForeignKey("main.Shop")
    transaction_type = models.CharField(max_length=7,choices=TRANSACTION_CATEGORIES,default="income",blank=True) 
    transaction_category = models.ForeignKey("finance.TransactionCategory",blank=True,null=True) 

    sale = models.ForeignKey("sales.Sale",null=True,blank=True,related_name="sale%(class)s_objects")
    sale_return = models.ForeignKey("sales.SaleReturn",null=True,blank=True,related_name="sale_return%(class)s_objects")
    purchase_return = models.ForeignKey("sales.ProductReturn",null=True,blank=True,related_name="purchase_return%(class)s_objects")
    collect_amount = models.ForeignKey("sales.CollectAmount",null=True,blank=True,related_name="collect_amount%(class)s_objects")
    customer_payment = models.ForeignKey("sales.CustomerPayment",null=True,blank=True,related_name="customer_payment%(class)s_objects")
    vender_payment = models.ForeignKey("purchases.CollectAmounts",null=True,blank=True,related_name="customer_payment%(class)s_objects")
    purchase = models.ForeignKey("purchases.Purchase",null=True,blank=True)
    asset_purchase = models.ForeignKey("purchases.AssetPurchase",null=True,blank=True)
    paid = models.ForeignKey("purchases.PaidAmount",null=True,blank=True)
    customer = models.ForeignKey("customers.Customer",null=True,blank=True)
    vendor = models.ForeignKey("vendors.Vendor",null=True,blank=True)
    staff_salary = models.ForeignKey('staffs.StaffSalary',blank=True,null=True)
    booking = models.ForeignKey('bookings.Booking',blank=True,null=True)
    checkin = models.ForeignKey('bookings.Checkin',blank=True,null=True)
    checkout = models.ForeignKey('bookings.Checkout',blank=True,null=True)

    transaction_mode = models.CharField(max_length=15,choices=TRANSACTION_MODE,default="cash")
    payment_mode = models.CharField(max_length=128,choices=PAYMENT_MODE,blank=True,null=True)
    cheque_details = models.CharField(max_length=128,null=True,blank=True)
    is_cheque_withdrawed = models.BooleanField(default=False)
    card_details = models.CharField(max_length=128,null=True,blank=True)
    payment_to = models.CharField(max_length=128,choices=PAYMENT_TO,default="cash_account",null=True,blank=True)              
    bank_account = models.ForeignKey("finance.BankAccount",null=True,blank=True)
    cash_account = models.ForeignKey("finance.CashAccount",null=True,blank=True)        
    amount = models.DecimalField(decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))],null=True,blank=True)
    description = models.CharField(max_length=128,blank=True,null=True)   
    
    date = models.DateTimeField()    
    first_transaction = models.BooleanField(default=False)
    
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transaction'
        verbose_name = 'transaction'
        verbose_name_plural = 'transactions'
        ordering = ('-date',)
        
    class Admin:
        list_display = ('id', 'amount','transaction_type')
        
    def __unicode__(self):
        return self.id


class StaffSalaryPayment(BaseModel):
    shop = models.ForeignKey("main.Shop")
    staff_salary = models.ForeignKey("staffs.StaffSalary",null=True,blank=True)
    transaction = models.ForeignKey("finance.Transaction",null=True,blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])  
   
    
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'staff_salary_payment'
        verbose_name = 'staff salary payment'
        verbose_name_plural = 'staff salary payments'
        ordering = ('a_id',)
        
    class Admin:
        list_display = ('transaction', 'staff_salary', 'amount')
        
    def __unicode__(self):
        return self.amount

templates/finance/transaction.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>
    
                <div class="ah-search">
                    <form method="get" action="{% url 'finance:transactions' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
    
                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>
    
                <ul class="ah-actions actions a-alt">
                    <li>
                        <a data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'finance:delete_transaction' pk=instance.pk %}" class="action-button redirect"><i class="zmdi zmdi-delete"></i></a>
                    </li> 
                    <li>
                    {% if instance.transaction_type == "income" %}
                        {% if instance.collect_amount != NULL%}
                            <a href="{% url 'sales:edit_collect_amount' pk=instance.collect_amount.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% elif instance.sale != NULL and instance.collect_amount == NULL%}
                            <a href="{% url 'sales:edit' pk=instance.sale.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% else %}
                            <a href="{% url 'finance:edit_income' pk=instance.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% endif %}
                    {% endif %}
                    {% if instance.transaction_type == "expense" %}
                        {% if instance.paid != NULL%}
                            <a href="{% url 'purchases:edit_paid' pk=instance.paid.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% elif instance.purchase != NULL and instance.paid == NULL%}
                            <a href="{% url 'purchases:edit_purchase' pk=instance.purchase.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% elif instance.staff != NULL %}
                            <a href="{% url 'finance:edit_salary_payment'  pk=instance.pk %}"><i class="zmdi zmdi-edit"></i></a>
                        {% else %}
                            <a href="{% url 'finance:edit_expense' pk=instance.pk %}" ><i class="zmdi zmdi-edit"></i></a>
                        {% endif %}
                    {% endif %} 
                    </li>  
                </ul>
             </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Basic Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Name</div>
                                    {% if instance.staff != NULL %}
                                        <small class="lgi-text">{{instance.staff.first_name|default:"-"}}</small>
                                    {% elif instance.shop != NULL %}
                                        <small class="lgi-text">{{instance.shop.name|default:"-"}}</small>
                                    {% else %}
                                        <small class="lgi-text">{{instance.transaction_category.name|default:"-"}}</small>
                                    {% endif %}


                                </div>
                            </div>
                        	
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Type</div>
                                    <small class="lgi-text">{{instance.get_transaction_type_display|default:"-"}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Date</div>
                                    <small class="lgi-text">{{instance.date|default:"-"}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Amount</div>
                                    <small class="lgi-text">{{instance.amount|default:"-"}}</small>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h2>Transaction Details<small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Transaction Mode</div>
                                    <small class="lgi-text">{{instance.get_transaction_mode_display|default:"-"}}</small>
                                </div>
                            </div>
                            {% if instance.payment_mode %}
                            
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Payment Mode</div>
                                    <small class="lgi-text">{{instance.get_payment_mode_display|default:"-"}}</small>
                                </div>
                            </div>
                            {% endif %}
                            {% if instance.cheque_details %}
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Cheque Details</div>
                                    <small class="lgi-text">{{instance.cheque_details|default:"-"}}</small>
                                </div>
                            </div>

                            {% endif %}
                            {% if instance.cheque_details %}
                             <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Is Cheque Withdrawed</div>
                                    <small class="lgi-text">{{instance.is_cheque_withdrawed|yesno:"Yes,No"}}</small>
                                </div>
                            </div>
                            {% endif %}
                            {% if instance.card_details %}
                             <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Card Details</div>
                                    <small class="lgi-text">{{instance.card_details|default:"-"}}</small>
                                </div>
                            </div>
                            {% endif %}
                            {% if instance.payment_to and instance.transaction_mode == "bank" %}
                             <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Payment to</div>
                                    <small class="lgi-text">{{instance.get_payment_to_display|default:"-"}}</small>
                                </div>
                            </div>
                            {% endif %}
                            {% if instance.bank_account %}
                             <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Bank Account</div>
                                    {% if request.user.is_superuser or 'can_view_bank_account' in user_instance.permissionlist %}
                                        <b class="info"><a href="{% url 'finance:bank_account' pk=instance.bank_account.pk %}">{{instance.bank_account.name|default:"-"}}</a></b>
                                    {% else %}
                                    <small class="lgi-text">{{instance.bank_account.name|default:"-"}}</small>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}
                            {% if instance.cash_account %}
                             <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Cash Account</div>
                                    {% if request.user.is_superuser or 'can_view_cash_account' in user_instance.permissionlist %}
                                        <b class="info"><a href="{% url 'finance:cash_account' pk=instance.cash_account.pk %}">{{instance.cash_account.name|default:"-"}}</a></b>
                                    {% else %}
                                    <small class="lgi-text">{{instance.cash_account.name|default:"-"}}</small>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                
                <div class="card">
                    <div class="card-header">
                        <h2>Created &amp; Updated <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Added</div>
                                    <small class="lgi-text">{{instance.date_added}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Updated</div>
                                    <small class="lgi-text">{{instance.date_updated}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Created User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.creator.username %}">{{instance.creator.username|get_user_name}}</a></small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Last Updated User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.updator.username %}">{{instance.updator.username|get_user_name}}</a></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
             </div>                    
        </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}