finance/urls.py
from django.conf.urls import url
import views
from finance.autocomplete_light_registry import StaffAutocomplete, TaxCategoryAutocomplete


urlpatterns = [
    url(r'^tax_category-autocomplete/$',TaxCategoryAutocomplete.as_view(create_field='tax'),name='tax_category_autocomplete'),

    url(r'^$', views.dashboard,name='dashboard'), 

    url(r'^bank-account/create/$',views.create_bank_account,name='create_bank_account'),
    url(r'^bank-account/edit(?P<pk>.*)/$',views.edit_bank_account,name='edit_bank_account'),
    url(r'^bank-accounts/$',views.bank_accounts,name='bank_accounts'),
    url(r'^bank-account/view/(?P<pk>.*)/$',views.bank_account,name='bank_account'),
    url(r'^bank-account/delete/(?P<pk>.*)/$',views.delete_bank_account,name='delete_bank_account'),
    url(r'^bank-account/delete-selected/$', views.delete_selected_bank_accounts, name='delete_selected_bank_accounts'),

    url(r'^cash-account/create/$',views.create_cash_account,name='create_cash_account'),
    url(r'^cash-account/edit/(?P<pk>.*)$',views.edit_cash_account,name='edit_cash_account'),
    url(r'^cash-accounts/$',views.cash_accounts,name='cash_accounts'),
    url(r'^cash-account/view/(?P<pk>.*)/$',views.cash_account,name='cash_account'),
    url(r'^cash-account/delete/(?P<pk>.*)$',views.delete_cash_account,name='delete_cash_account'),
    url(r'^cash-account/delete-selected/$', views.delete_selected_cash_accounts, name='delete_selected_cash_accounts'),

    url(r'^transaction-category/create/$',views.create_transaction_category,name='create_transaction_category'),
    url(r'^transaction-category/edit/(?P<pk>.*)/$',views.edit_transaction_category,name='edit_transaction_category'),
    url(r'^transaction-categories/',views.transaction_categories,name='transaction_categories'),
    url(r'^transaction-category/view/(?P<pk>.*)/$',views.transaction_category,name='transaction_category'),
    url(r'^transaction-category/delete/(?P<pk>.*)/$',views.delete_transaction_category,name='delete_transaction_category'),
    url(r'^transaction-category/delete-selected/$', views.delete_selected_transaction_categories, name='delete_selected_transaction_categories'),

    url(r'^income/create/$',views.create_income,name='create_income'),
    url(r'^income/edit/(?P<pk>.*)/$',views.edit_income,name='edit_income'),
    
    url(r'^transactions/$',views.transactions,name='transactions'),
    url(r'^transaction/view/(?P<pk>.*)/$',views.transaction,name='transaction'),
    url(r'^transaction/delete/(?P<pk>.*)/$',views.delete_transaction,name='delete_transaction'),
    url(r'^transaction/delete-selected/$', views.delete_selected_transactions, name='delete_selected_transactions'),

    url(r'^expense/create/$',views.create_expense,name='create_expense'),
    url(r'^expense/edit(?P<pk>.*)/$',views.edit_expense,name='edit_expense'),
    
    url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staff_autocomplete'),

    url(r'^tax-category/create/$', views.create_tax_category, name='create_tax_category'),
    url(r'^tax-categories/$', views.tax_categories, name='tax_categories'),
    url(r'^tax-category/edit/(?P<pk>.*)/$', views.edit_tax_category, name='edit_tax_category'),
    url(r'^tax-category/(?P<pk>.*)/$', views.tax_category, name='tax_category'),
    url(r'^delete-tax-category/(?P<pk>.*)/$', views.delete_tax_category, name='delete_tax_category'),
    url(r'^tax-category/delete-selected/$', views.delete_selected_tax_categories, name='delete_selected_tax_categories'),

    url(r'^create-salary-payment/$',views.create_salary_payment,name='create_salary_payment'),
    url(r'^create-salary-payment-popup/$',views.create_salary_payment_ajax,name='create_salary_payment_ajax'),
    url(r'^salary-payment/edit/(?P<pk>.*)/$',views.edit_salary_payment,name='edit_salary_payment'),
    url(r'^salary-payments/$',views.salary_payments,name='salary_payments'),
    
]

hotel_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^web/', include('web.urls', namespace="web")), 

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),
      
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'), 
    
    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")), 
    url(r'^app/rooms/', include('rooms.urls', namespace="rooms")), 
    url(r'^app/bookings/', include('bookings.urls', namespace="bookings")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")), 
    url(r'^app/staffs/', include('staffs.urls', namespace='staffs')),
    url(r'^app/vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^app/purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^app/finance/', include('finance.urls', namespace="finance")),
    url(r'^app/tasks/', include('tasks.urls', namespace="tasks")),
    
    url(r'^app/users/', include('users.urls', namespace="users")), 

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),
    
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

staffs/urls.py
from django.conf.urls import url
import views
from staffs.views import DesignationAutocomplete,StaffAutocomplete

urlpatterns = [
    url(r'^designation-autocomplete/$',DesignationAutocomplete.as_view(create_field='name'),name='designation_autocomplete'),
	url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staffs_autocomplete'),

    url(r'^designation/create/$', views.create_designation, name='create_designation'),
    url(r'^designations/$', views.designations, name='designations'),
    url(r'^designation/edit/(?P<pk>.*)/$', views.edit_designation, name='edit_designation'),
    url(r'^designation/(?P<pk>.*)/$', views.designation, name='designation'),
    url(r'^delete-designation/(?P<pk>.*)/$', views.delete_designation, name='delete_designation'),
    url(r'^designation/delete-selected/$', views.delete_selected_designations, name='delete_selected_designations'),

    url(r'^staff/create/$', views.create_staff, name='create_staff'),
    url(r'^staffs/$', views.staffs, name='staffs'),
    url(r'^staff/edit/(?P<pk>.*)/$', views.edit_staff, name='edit_staff'),
    url(r'^staff/(?P<pk>.*)/$', views.staff, name='staff'),
    url(r'^staff-delete/(?P<pk>.*)/$', views.delete_staff, name='delete_staff'),
    url(r'^staff/delete-selected/$', views.delete_selected_staffs, name='delete_selected_staffs'),

    url(r'^staff-salary/create/$',views.create_staff_salary,name='create_staff_salary'),
    url(r'^staff-salaries/view/$',views.staff_salaries,name='staff_salaries'),
    url(r'^staff-salary/view/(?P<pk>.*)/$',views.staff_salary,name='staff_salary'),
    url(r'^staff-salary/edit/(?P<pk>.*)/$',views.edit_staff_salary,name='edit_staff_salary'),
    url(r'^staff-salary/delete/(?P<pk>.*)/$',views.delete_staff_salary,name='delete_staff_salary'),
    url(r'^delete-selected-staff-salaries/$', views.delete_selected_staff_salaries, name='delete_selected_staff_salaries'),

    url(r'^get-salary/$',views.get_salary,name='get_salary'),

]

users/urls.py
from django.conf.urls import patterns, url,include
import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^view/(?P<pk>.*)/$', views.view, name='view'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    url(r'^settings/$', views.settings, name='settings'), 
    url(r'^settings/update-shop/$', views.update_shop, name='update_shop'),

    url(r'^user/create/(?P<pk>.*)/$', views.create_user, name='create_user'),
    url(r'^user/view/(?P<pk>.*)/$', views.view_user, name='view_user'),
    url(r'^users/$', views.users, name='users'), 
    url(r'^user/delete/(?P<pk>.*)/$', views.delete_user, name='delete_user'),
    url(r'^user/delete-selected/$', views.delete_selected_users, name='delete_selected_users'),
    url(r'^change-permissions/(?P<pk>.*)/$', views.change_permissions, name='change_permissions'),
    url(r'^change-password/(?P<pk>.*)/$', views.change_password, name='change_password'),

    url(r'^revoke-access/(?P<pk>.*)/$', views.revoke_access, name='revoke_access'), 
    
    
]

web/urls.py
from django.conf.urls import url,include
import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

staffs/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from main.models import BaseModel, Shop
from decimal import Decimal


GENDER_CHOICES = (
    ('M','Male'),
    ('F','Female'),
    ('O','Other')
)

SALARY_TYPE = (
    ('daily','Daily'),
    ('monthly','Monthly')
)

MONTH = (
    ('1','January'),
    ('2','February'),
    ('3','March'),
    ('4','April'),
    ('5','May'),
    ('6','June'),
    ('7','July'),
    ('8','August'),
    ('9','September'),
    ('10','October'),
    ('11','November'),
    ('12','December'),
)


class Designation(BaseModel):
    shop = models.ForeignKey("main.Shop")
    name = models.CharField(max_length=128)

    is_deleted = models.BooleanField(default=False)

    class Meta:
        db_table = 'staffs_designation'
    	verbose_name = _('designation')
    	verbose_name_plural = _('designations')

    def __unicode__(self):
        return self.name


class Staff(BaseModel):
    shop = models.ForeignKey("main.Shop")
    user = models.OneToOneField("auth.user",blank=True,null=True)
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128,blank=True,null=True)
    phone = models.CharField(max_length=15,null=True)
    gender = models.CharField(max_length=5,choices=GENDER_CHOICES)
    dob = models.DateField(blank=True,null=True)
    joined_date = models.DateField()
    salary_type = models.CharField(max_length=30,choices=SALARY_TYPE)
    designation = models.ForeignKey("staffs.Designation")
    salary = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    photo = models.ImageField(upload_to="uploads/staffs/",blank=True,null=True)
    permissions = models.ManyToManyField("users.Permission")
    
    credit = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    debit = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

    is_deleted = models.BooleanField(default=False)

    def permissionlist(self):
        permlist = list(set([x.code for x in self.permissions.all()]))
        
        return permlist
        
    class Meta:
        db_table = 'staffs_staff'
        verbose_name = _('staff')
    	verbose_name_plural = _('staffs')

    def __unicode__(self):
        return self.first_name +" " + self.last_name


class StaffSalary(BaseModel):
    shop = models.ForeignKey("main.Shop")
    staff = models.ForeignKey("staffs.Staff")
    date = models.DateField()
    month = models.CharField(max_length=128,choices=MONTH)
    year = models.PositiveIntegerField()
    basic_salary = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    amount = models.DecimalField(decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
    allowance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))]) 
    deduction = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])       
    paid = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])    
    balance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])    
    advance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])    
    
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'staffs_staffsalary'
        verbose_name = _('staffsalary')
        verbose_name_plural = _('staffsalaries')
        ordering = ('-a_id',)
        
    def __unicode__(self):
        return str(self.amount)

templates/staffs/staff_salaries.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
	            <div class="ah-label hidden-xs palette-White text">{{title}}</div>
	
	            <div class="ah-search">
	            	<form method="get" action="{% url 'staffs:staff_salaries' %}">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
	
	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>
	
	            <ul class="ah-actions actions a-alt">
                    {% if is_superuser or 'can_view_staff_salary' in user_instance.permissionlist or 'can_view_staff_salary' in staff_instance.designation.permissionlist %}
    	                <li>
    	                    <a href="{% url 'staffs:staff_salaries' %}" class="ah-search-trigger" data-ma-action="ah-search-open">
    	                        <i class="zmdi zmdi-search"></i>
    	                    </a>
    	                </li>
	                {% endif %}
	                <li>
	                    <a title="Filter" class="filter_button" href="">
	                        <i class="zmdi zmdi-filter-list"></i>
	                    </a>
	                </li>
	                {% if is_superuser or 'can_create_staff_salary' in user_instance.permissionlist or 'can_create_staff_salary' in staff_instance.designation.permissionlist %}
    	                <li>
                            <a title="Create staff salary" href="{% url 'staffs:create_staff_salary' %}">
                                <i class="zmdi zmdi-plus"></i>
                            </a>
                        </li>
                    {% endif %}
                    {% if is_superuser or 'can_create_salary_payment' in user_instance.permissionlist or 'can_create_salary_payment' in staff_instance.designation.permissionlist %}
                         <li>
                            <a title="Create Salary Payment" href="{% url 'finance:create_salary_payment'%}">
                                <i class="zmdi zmdi-money"></i>
                            </a>
                        </li>
	                {% endif %}
	                {% if instances %}
    	
    	                <li>
    	                    <a title="Select All" class="check_all" href="">
    	                        <i class="zmdi zmdi-select-all"></i>
    	                    </a>
    	                </li>
    	                {% if is_superuser or 'can_delete_staff_salary' in user_instance.permissionlist or 'can_delete_staff_salary' in staff_instance.designation.permissionlist %}
        	                <li>
        	                    <a title="Delete selected items" data-id="" href="{% url 'staffs:delete_selected_staff_salaries' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
        	                        <i class="zmdi zmdi-delete"></i>
        	                    </a>
        	                </li>
                        {% endif %}
	                {% endif %}
	            </ul>
	            
	        </div>

            <div class="card">
				
				{% if instances %}
                
                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                            	<th style="width:20px;"></th>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Staff</th>
                                <th>Date</th>
                                <th>Month</th>
                                <th>Amount</th>
                                <th>Paid</th>
                                <th>Balance</th>
                                <th data-column-id="action"></th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% load el_pagination_tags %}
							{% paginate 21 instances %}
                        	{% for instance in instances %}
                            <tr class="check_items_row">
                            	<td style="width:20px;">
                            		<div class="checkbox lgi-checkbox m-t-5">
			                            <label>
			                                <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
			                                <i class="input-helper"></i>
			                            </label>
			                        </div>
                            	</td>
                                <td>{{instance.a_id}}</td>
                                <td>{{instance.staff}}</td>
                                <td>{{instance.date}}</td>
                                <td>{{instance.month}}/{{instance.year}}</td>
                                <td>{{instance.amount }}</td> 
                                <td>{{instance.paid }}</td>    
                                <td>{{instance.balance }}</td> 
                                <td>
                                    {% if is_superuser or 'can_view_staff_salary' in user_instance.permissionlist or 'can_view_staff_salary' in staff_instance.designation.permissionlist %}
                                	   <a href="{% url 'staffs:staff_salary' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    {% endif %}
                                    {% if is_superuser or 'can_modify_staff_salary' in user_instance.permissionlist or 'can_modify_staff_salary' in staff_instance.designation.permissionlist %}
                                	   <a href="{% url 'staffs:edit_staff_salary' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% endif %}
                                    {% if is_superuser or 'can_delete_staff_salary' in user_instance.permissionlist or 'can_delete_staff_salary' in staff_instance.designation.permissionlist %}
                                	   <a data-id="{{instance.pk}}" href="{% url 'staffs:delete_staff_salary' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>   
                <!--pagination-->
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}            
            </div>
            
        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'staffs:staff_salaries' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>
		    
			<div class="card-body card-padding add_item_container sale_item_formset">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>

                <div class="form-group fg-line">
                    <label for="id_month">Month</label>
                    <select name="month_filter" id="id_month" class="selectpicker">
                        <option value="">All</option>
                        <option value="1">January</option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select>
                </div>
                 <div class="form-group fg-line">
                    <label>Year</label>
                    <input name="year" type="text" class="form-control" placeholder="Enter year" />
                </div>
                <div class="form-group fg-line">
                    <label>Date</label>
                    <input name="date" type="text" class="form-control date-picker" placeholder="Enter date" />
                </div>
                <div class="form-group fg-line">
                    <label>From Date</label>
                    <input name="from_date" type="text" class="form-control date-picker" placeholder="Enter from date" />
                </div>
                <div class="form-group fg-line">
                    <label>To Date</label>
                    <input name="to_date" type="text" class="form-control date-picker" placeholder="Enter to date" />
                </div>
		        
		         <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}