bookings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from sales.views import SaleAutocomplete,ReturnableProductAutocomplete


urlpatterns = [               
    url(r'^booking-autocomplete/$',SaleAutocomplete.as_view(),name='booking_autocomplete'),
    
    url(r'^booking/create/$',views.create_booking,name='create_booking'),
    url(r'^booking/views/$',views.bookings,name='bookings'),
    url(r'^booking/edit/(?P<pk>.*)/$',views.edit_booking,name='edit_booking'),
    url(r'^booking/view/(?P<pk>.*)/$',views.booking,name='booking'),
    url(r'^booking/delete/(?P<pk>.*)/$',views.delete_booking,name='delete_booking'),
    url(r'^booking/delete-selected/$', views.delete_selected_bookings, name='delete_selected_bookings'),
    url(r'^invoice/(?P<pk>.*)/$',views.print_booking,name='print_booking'),
    url(r'^email/(?P<pk>.*)/$',views.email_booking,name='email_booking'),  

    url(r'^checkin-from-boking/create/(?P<pk>.*)$',views.create_checkin_booking,name='create_checkin_booking'),

    url(r'^get-vacant-rooms/$', views.get_vacant_rooms,name='get_vacant_rooms'), 

    url(r'^checkin/create/$',views.create_checkin,name='create_checkin'),
    url(r'^checkin/views/$',views.checkins,name='checkins'),
    url(r'^checkin/edit/(?P<pk>.*)/$',views.edit_checkin,name='edit_checkin'),
    url(r'^checkin/view/(?P<pk>.*)/$',views.checkin,name='checkin'),
    url(r'^checkin/delete/(?P<pk>.*)/$',views.delete_checkin,name='delete_checkin'),
    url(r'^checkin/delete-selected/$', views.delete_selected_checkins, name='delete_selected_checkins'),
    url(r'^print/checkin/(?P<pk>.*)/$',views.print_checkin,name='print_checkin'),
    url(r'^email/(?P<pk>.*)/$',views.email_checkin,name='email_checkin'),  

    url(r'^checkout/create/(?P<pk>.*)/$', views.create_checkout, name='create_checkout'),
    url(r'^checkout/view/(?P<pk>.*)/$', views.checkout, name='checkout'),
    url(r'^checkout/edit/(?P<pk>.*)/$', views.edit_checkout, name='edit_checkout'),
    url(r'^checkouts/$', views.checkouts, name='checkouts'),
    url(r'^checkout/delete/(?P<pk>.*)/$', views.delete_checkout, name='delete_checkout'),
    url(r'^checkout/delete-selected/$', views.delete_selected_checkouts, name='delete_selected_checkouts'),
    url(r'^checkout/print/(?P<pk>.*)/$',views.print_checkout,name='print_checkout'),
    url(r'^checkouts/print/$',views.print_checkouts,name='print_checkouts'), 
]

customers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from customers.views import CustomerAutocomplete


urlpatterns = [               
    url(r'^customer-autocomplete/$',CustomerAutocomplete.as_view(),name='customer_autocomplete'),
    
    url(r'^$', views.dashboard,name='dashboard'), 
    
    url(r'^customer/create/$',views.create,name='create'),
    url(r'^customer/view/$',views.customers,name='customers'),
    url(r'^customer/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^customer/views/(?P<pk>.*)/$',views.customer,name='customer'),
    url(r'^customer/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^customer/delete-selected/$', views.delete_selected_customers, name='delete_selected_customers'), 

    url(r'^get-debit/$', views.get_credit, name='get_credit'),
    url(r'^check-document/$', views.check_document, name='check_document'),
]

hotel_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^web/', include('web.urls', namespace="web")), 

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),
      
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'), 
    
    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")), 
    url(r'^app/rooms/', include('rooms.urls', namespace="rooms")), 
    url(r'^app/bookings/', include('bookings.urls', namespace="bookings")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")), 
    url(r'^app/staffs/', include('staffs.urls', namespace='staffs')),
    url(r'^app/vendors/', include('vendors.urls', namespace='vendors')),
    url(r'^app/purchases/', include('purchases.urls', namespace='purchases')),
    url(r'^app/finance/', include('finance.urls', namespace="finance")),
    url(r'^app/tasks/', include('tasks.urls', namespace="tasks")),
    
    url(r'^app/users/', include('users.urls', namespace="users")), 

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),
    
    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

sales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from sales.views import SaleAutocomplete,ReturnableProductAutocomplete


urlpatterns = [               
    url(r'^sale-autocomplete/$',SaleAutocomplete.as_view(),name='sale_autocomplete'),
    url(r'^returnable_products-autocomplete/$',ReturnableProductAutocomplete.as_view(),name='returnable_product_autocomplete'),
    
    url(r'^$', views.dashboard,name='dashboard'), 
    url(r'^print-report/$', views.print_report,name='print_report'), 
    url(r'^taxed-sale-items/$', views.taxed_sale_items,name='taxed_sale_items'),
    url(r'^export-report/$', views.export_report,name='export_report'),
    
    url(r'^sale/create/$',views.create,name='create'),
    url(r'^sale/views/$',views.sales,name='sales'),
    url(r'^sale/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^sale/view/(?P<pk>.*)/$',views.sale,name='sale'),
    url(r'^sale/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^sale/delete-selected/$', views.delete_selected_sales, name='delete_selected_sales'),
    url(r'^invoice/(?P<pk>.*)/$',views.print_sale,name='print'),
    url(r'^email/(?P<pk>.*)/$',views.email_sale,name='email_sale'),

    url(r'^sale-items/views/$',views.sale_items,name='sale_items'),

    url(r'^collect-amount/create/$', views.create_collect_amount, name='create_collect_amount'),
    url(r'^collect-amount/view/(?P<pk>.*)/$', views.collect_amount, name='collect_amount'),
    url(r'^collect-amount/edit/(?P<pk>.*)/$', views.edit_collect_amount, name='edit_collect_amount'),
    url(r'^collect-amounts/$', views.collect_amounts, name='collect_amounts'),
    url(r'^collect-amount/delete/(?P<pk>.*)/$', views.delete_collect_amount, name='delete_collect_amount'),
    url(r'^collect-amount/delete-selected/$', views.delete_selected_collect_amounts, name='delete_selected_collect_amounts'),
    url(r'^collected-amount/print/(?P<pk>.*)/$',views.print_collected_amount,name='print_collected_amount'),
    url(r'^collected-amounts/print/$',views.print_collected_amounts,name='print_collected_amounts'),

    url(r'^customer-payment/create/$', views.create_customer_payment, name='create_customer_payment'),
    url(r'^customer-payment/view/(?P<pk>.*)/$', views.customer_payment, name='customer_payment'),
    url(r'^customer-payment/edit/(?P<pk>.*)/$', views.edit_customer_payment, name='edit_customer_payment'),
    url(r'^customer-payments/$', views.customer_payments, name='customer_payments'),
    url(r'^customer-payment/delete/(?P<pk>.*)/$', views.delete_customer_payment, name='delete_customer_payment'),
    url(r'^customer-payment/delete-selected/$', views.delete_selected_customer_payments, name='delete_selected_customer_payments'),
    url(r'^customer-payment/print/(?P<pk>.*)/$',views.print_customer_payment,name='print_customer_payment'),
    url(r'^customer-payments/print/$',views.print_customer_payments,name='print_customer_payments'),

    url(r'^create-sale-return/$',views.create_sale_return,name='create_sale_return'),
    url(r'^sale-returns/$',views.sale_returns,name='sale_returns'), 
    url(r'^sale-return/(?P<pk>.*)/$', views.sale_return, name='sale_return'),
    url(r'^edit-sale-return/(?P<pk>.*)/$', views.edit_sale_return, name='edit_sale_return'),
    url(r'^delete-sale-return/(?P<pk>.*)/$', views.delete_sale_return, name='delete_sale_return'),

    url(r'^create-damaged-product/$',views.create_damaged_product,name='create_damaged_product'),
    url(r'^damaged-products/$',views.damaged_products,name='damaged_products'), 
    url(r'^damaged-product/(?P<pk>.*)/$', views.damaged_product, name='damaged_product'),
    url(r'^edit-damaged-product/(?P<pk>.*)/$', views.edit_damaged_product, name='edit_damaged_product'),
    url(r'^delete-damaged-product/(?P<pk>.*)/$', views.delete_damaged_product, name='delete_damaged_product'),

    url(r'^returnable-products/$',views.returnable_products,name='returnable_products'),
    url(r'^returnable-product/view(?P<pk>.*)/$',views.returnable_product,name='returnable_product'),
    url(r'^returnable-product/delete/(?P<pk>.*)/$', views.delete_returnable_product, name='delete_returnable_product'),
    url(r'^returnable-product/delete-selected/$', views.delete_selected_returnable_products, name='delete_selected_returnable_products'),

    url(r'^create-product-return/$',views.create_product_return,name='create_product_return'),
    url(r'^product-return/(?P<pk>.*)/$', views.product_return, name='product_return'),
    url(r'^product-returns/$',views.product_returns,name='product_returns'),
    url(r'^delete-product-return/(?P<pk>.*)/$', views.delete_product_return, name='delete_product_return'),

    url(r'^create-damaged-product/$',views.create_damaged_product,name='create_damaged_product'),
    url(r'^damaged-products/$',views.damaged_products,name='damaged_products'), 
    url(r'^damaged-product/(?P<pk>.*)/$', views.damaged_product, name='damaged_product'),
    url(r'^edit-damaged-product/(?P<pk>.*)/$', views.edit_damaged_product, name='edit_damaged_product'),
    url(r'^delete-damaged-product/(?P<pk>.*)/$', views.delete_damaged_product, name='delete_damaged_product'),

    url(r'^get-sale-items/$', views.get_sale_items,name='get_sale_items'),
    url(r'^get-customer/$', views.get_customer,name='get_customer'),

    url(r'^estimate/create/$',views.create_estimate,name='create_estimate'),
    url(r'^estimate/views/$',views.estimates,name='estimates'),
    url(r'^estimate/edit/(?P<pk>.*)/$',views.edit_estimate,name='edit_estimate'),
    url(r'^estimate/view/(?P<pk>.*)/$',views.estimate,name='estimate'),
    url(r'^estimate/delete/(?P<pk>.*)/$',views.delete_estimate,name='delete_estimate'),
    url(r'^estimate/delete-selected/$', views.delete_selected_estimates, name='delete_selected_estimates'),
    url(r'^print-estimate/(?P<pk>.*)/$',views.print_estimate,name='print_estimate'),
    url(r'^email-estimate/(?P<pk>.*)/$',views.email_estimate,name='email_estimate'),

    url(r'^stock/report/$',views.stock_report, name='stock_report'),
]

vendors/urls.py
from django.conf.urls import url
from vendors.views import VendorAutocomplete
import views


urlpatterns = [

    url(r'^vendor-autocomplete/$',VendorAutocomplete.as_view(),name='vendor_autocomplete'),


    url(r'^vendor/create/$', views.create_vendor, name='create_vendor'),
    url(r'^vendors/$', views.vendors, name='vendors'),
    url(r'^vendor/edit/(?P<pk>.*)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^vendor/view/(?P<pk>.*)/$', views.vendor, name='vendor'),
    url(r'^vendor/delete/(?P<pk>.*)/$', views.delete_vendor, name='delete_vendor'),
    url(r'^vendor/delete-selected/$', views.delete_selected_vendors, name='delete_selected_vendors'),

    url(r'^get-debit/$', views.get_debit, name='get_debit'),
]

web/urls.py
from django.conf.urls import url,include
import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

templates/includes/dashboard/month_report.html
<div class="card c-dark palette-Blue bg">
    <div class="card-header p-b-0">
        <h2>For the past 30 days</h2>
    </div>
    <div class="card-body">
        <div class="chart-edge">
            <div class="ns-chart flot-chart" id="number-stats-chart"></div>
        </div>

        <div class="list-group lg-alt lg-even-white">
            <div class="list-group-item media">
                <div class="pull-right hidden-sm">
                    <div class="sparkline-bar-1"></div>
                </div>

                <div class="media-body ns-item">
                    <small>Page Views</small>
                    <h3>47,896,536</h3>
                </div>
            </div>

            <div class="list-group-item media">
                <div class="pull-right hidden-sm">
                    <div class="sparkline-bar-2"></div>
                </div>

                <div class="media-body ns-item">
                    <small>Site Visitors</small>
                    <h3>24,456,799</h3>
                </div>
            </div>

            <div class="list-group-item media">
                <div class="pull-right hidden-sm">
                    <div class="sparkline-bar-3"></div>
                </div>

                <div class="media-body ns-item">
                    <small>Total Clicks</small>
                    <h3>13,965</h3>
                </div>
            </div>
        </div>

        <div class="p-5"></div>
    </div>
</div>

templates/includes/dashboard/recent_checkout.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Check Out <small></small></h2>
    </div>

    <div class="card-body">
        <div class="table-responsive">
        	{% if recent_checkout %}
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Time</th>
                        <th>Customer</th>
                        <th>Total Days</th>
                        <th>Collect Amount</th>
                        <th>Balance</th>
                        <th data-column-id="action" class="four">Action</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_checkout %}
                    <tr>
                        <td><a href="{% url 'bookings:checkout' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.date}}</td>
                        <td><a href="{% url 'customers:customer' pk=instance.customer.pk %}">{{instance.customer}}</a></td>
                        <td>{{instance.checkin.total_days}}</td>
                        <td>{{instance.collect_amount}}</td>
                        <td>{{instance.balance}}</td>
                        <td class="four">
                        	<a href="{% url 'bookings:checkout' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                        	<a href="{% url 'bookings:edit_checkout' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                        	<a data-id="{{instance.pk}}" href="{% url 'bookings:delete_checkout' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                        	<a target='_blank' href="{% url 'bookings:print_checkout' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-print"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% else %}
            	<div class="card-body card-padding">
	            	<p>No Checkout found</p>
	            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_customers.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Customers <small></small></h2>
    </div>

    <div class="card-body">
    	{% if recent_customers %}
        <div class="list-group lg-alt c-overflow">
        	{% for customer in recent_customers %}
            <a href="{% url 'customers:customer' pk=customer.pk %}" class="list-group-item media">
                <div class="pull-left">
                    <img class="avatar-img" src="{% static 'img/profile-pics/1.jpg' %}" alt="">
                </div>

                <div class="media-body">
                    <div class="lgi-heading">{{customer.name}}</div>
                    <small class="lgi-text">{{customer.phone}} - {{customer.email}} - {{customer.address}}</small>
                </div>
            </a>
            {% endfor %}
            
            <a href="{% url 'customers:customers' %}" class="list-group-item view-more">
                <i class="zmdi zmdi-long-arrow-right"></i> View all
            </a>
        </div>
        
        {% else %}
        	<div class="card-padding card-body">
	        	<p>No customers found</p>
	        </div>
        {% endif %}
    </div>
</div>

templates/includes/dashboard/recent_products.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Products <small></small></h2>
    </div>

    <div class="card-body">
    	{% if recent_products %}
        <div class="table-responsive">
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Name</th>
                        <th>Stock</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_products %}
                    <tr>
                        <td><a href="{% url 'products:product' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.name}}</td>
                        <td>{{instance.stock}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        	<div class="card-padding card-body">
	        	<p>No products found</p>
	        </div>
        {% endif %}
    </div>
</div>

templates/includes/dashboard/recent_purchase.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Purchase<small></small></h2>
    </div>

    <div class="card-body">
        <div class="table-responsive">
        	{% if recent_purchase %}
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Time</th>
                        <th>Vendor</th>
                        <th>Sub Total</th>
                        <th>Special Discount</th>
                        <th>Total</th>
                        <th data-column-id="action" class="four">Action</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_purchase %}
                    <tr>
                        <td><a href="{% url 'purchases:purchase' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.time}}</td>
                        <td><a href="{% url 'vendors:vendor' pk=instance.customer.pk %}">{{instance.vendor}}</a></td>
                        <td>{{instance.subtotal}}</td>
                        <td>{{instance.special_discount}}</td>
                        <td>{{instance.total}}</td>
                        <td class="four">
                        	<a href="{% url 'purchases:purchase' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                        	<a href="{% url 'purchases:edit_purchase' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                        	<a data-id="{{instance.pk}}" href="{% url 'purchases:delete_purchase' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                        	<a href="{% url 'purchases:print' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-print"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% else %}
            	<div class="card-body card-padding">
	            	<p>No purchases found</p>
	            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_sales.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Check In <small></small></h2>
    </div>

    <div class="card-body">
        <div class="table-responsive">
        	{% if recent_checkins %}
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Time</th>
                        <th>Customer</th>
                        <th>Total Days</th>
                        <th>Advance</th>
                        <th>Payment</th>
                        <th>Total</th>
                        <th data-column-id="action" class="four">Action</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_checkins %}
                    <tr>
                        <td><a href="{% url 'bookings:checkin' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.time}}</td>
                        <td><a href="{% url 'customers:customer' pk=instance.customer.pk %}">{{instance.customer}}</a></td>
                        <td>{{instance.total_days}}</td>
                        <td>{{instance.advance}}</td>
                        <td>{{instance.payment}}</td>
                        <td>{{instance.total}}</td>
                        <td class="four">
                        	<a href="{% url 'bookings:checkin' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                        	<a href="{% url 'bookings:edit_checkin' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                        	<a data-id="{{instance.pk}}" href="{% url 'bookings:delete_checkin' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                        	<a target='_blank' href="{% url 'bookings:print_checkin' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-print"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% else %}
            	<div class="card-body card-padding">
	            	<p>No Checkin found</p>
	            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/room_details.html
<div class="card card-padding">
    <div class="card-body card-padding">
     <h3>Room Details</h3>  
    </div>
    {% if rooms %}
     <div class="row m-b-10">
        {% for room in rooms %}
        <div class="col-md-1">
            {% if room.is_cleaning %}  
            <div class="card palette-theme teal bg"> 
            {% elif room.is_booked %}  
            <div class="card palette-theme green bg">
            {% elif room.is_vacant %} 
            <div class="card palette-theme blue bg">
            {% else %}
            <div class="card palette-theme purple-400 bg">
            {% endif %}                
                <div class="card-body card-padding tz-white">                 
                    <div class='d-l-b m-r-45'>
                        <small class="stats-label tz-white p-r-3 f-15 d-b">{{room.code}}</small>
                    </div>                    
                </div>
            </div>
        </div> 
        {% endfor %}           
    </div>
    {% endif %}
</div>
        